{include file='search.tpl'}
<div class="b2h" style="float:right;width:640px;margin-top:10px;"><div class="b2h_left"></div><div class="b2h_right"></div><h1>"Attract previously unreachable clients"<span style="font:italic 14px Arial;">- Roberto Vieira</span></h1></div>
<div class="bckgrd640" style="float:right;">
<p class="interview_q">Roberto Vieira is the CEO of BSE – a brazilian granite manufacturer and exporter. Below are excerpts from our interview with him.</p>
<p class="interview_q"><b>Slab Market:</b> Roberto, please give us some background information on your company.</p>
<p class="interview_a"><b>Roberto Vieira:</b> Our company, BSE, is a medium-sized manufacturer and exporter of natural stone slabs in Brazil. Before finding out about Slab Market, we usually sold our material to large fabricators and warehouses. While business has always been there from the large warehouses, my quarry’s vision is to expand and serve even the medium and small size fabricators directly. Up till now, we were unsuccessful in reaching them. These smaller fabricators are harder to find therefore I always had trouble sending a sales rep. They were often deterred by the legal paperwork of importing and just a general fear of making a mistake.  It was hard to earn the trust of a small fabricator that has never dealt with an overseas quarry.  I stumbled on www.slabmarket.com while looking for a new way to advertise my stone selection overseas. On my initial visit to the website, I was impressed by the friendly interface and the large number of quarries already using Slab Market. After looking around on the website I learned a surprising fact – All Granite and Marble (www.marble.com) is the company that runs Slab Market. I have sold slabs to All Granite before and know that they are one of the biggest natural stone fabricators in the United States.  With a trusted and respected company like AGM running the Slab Market, I felt at ease knowing that that the transaction is in good hands.  I was excited to try this innovative service and decided to register my quarry right away.</p>
<p class="interview_q"><b>Slab Market:</b> Please explain the process of signing up and listing your quarry with Slab Market.</p>
<p class="interview_a"><b>Roberto Vieira:</b> First I want to say that joining Slab Market is completely free. Because there are no fees, Slab Market attracts more companies like mine, promotes a healthy competition and gives them a chance to reach new clients across the globe. After signing up, the next step is to list the inventory up for sale. When adding stones, certain criteria must be included like name of the stone, thickness, size of slabs, and a basic description. If for example a particular type of slab for sale is available in 1¼ inch and ¾ inch thickness, it must be listed separately. It is also mandatory to attach photos of the stone so the client can see a clear visual of the color, grain, and pattern. I personally add close-ups so the client will be able to see all of the finer details. Listing the price is also recommended, but an option may be set to display “Inquire for Price” instead. In that case the client must contact Slab Market by phone or e-mail. Slab Market always makes sure to verify that the vendor is legitimate and that all requirements for listing are met before the slabs become available for purchase. Signing up with Slab Market is beneficial for me because I do not have to send any representatives overseas to try and persuade fabricators to buy from my quarry. This saves me time, resources, and most importantly money as my company is no longer responsible for the sales rep’s stay overseas (lodging and accommodations) and commission if they make a sale. Because the need to send sales reps is reduced, we gain big savings that we can incorporate into a lower price listing on www.slabmarket.com. This attracts more clients to us as we are able to be more competitive. On the website, all suppliers are listed by a number and their names are not shown. That is great because it allows to keep regular pricing for outside sales.</p>
<p class="interview_q"><b>Slab Market:</b> What happens when an order is placed through Slab Market?</p>
<p class="interview_a"><b>Roberto Vieira:</b> When purchasing slabs through Slab Market, the client usually fills up a container with material. While it is possible to just send one bundle out it is very impractical for the buyer because they will be charged for the shipping and handling of a whole container. Slab Market allows us to continuously sell a large quantities of slabs because clients generally fill up a container to maximize profit. After the fabricator’s virtual container is filled up, the Slab Market contacts the buyer to verify the order. At my quarry we then photograph each individual bundle that will be shipped so the fabricator can see exactly what they are getting. If the buyer requests a sample of the stone to see the texture and color, we gladly ship one out at no charge. After everything is good to go, the order is placed with my quarry. We then package the slabs into the shipment container. Any markings that may give away the quarry’s business name must be removed from all individual slabs to ensure anonymity and competitive pricing. We receive a 50% deposit at the start of the order and the rest is given once the slabs clear customs at the arriving destination. As the delivery arrives by freight to point of destination, Slab Market arranges transportation for the client and takes care of the legal paperwork which makes it a hassle-free experience for both sides. Slab Market makes the complicated process of importing and exporting natural stone really simple.</p>
<p class="interview_q"><b>Slab Market:</b> What are the main benefits of working with Slab Market?</p>
<p class="interview_a"><b>Roberto Vieira:</b> Working with www.slabmarket.com allowed me to get the exposure that we would never receive otherwise. We have doubled the number of sales to fabricators. By displaying my selection of granite on the internet with a trusted company like All Granite and Marble, I am reaching an audience that would have never heard of my quarry otherwise. The internet is the ultimate advertising tool in the 21st century and by taking advantage of this technology I am giving my business a very promising future. Slab Market perfectly complements my advertising strategy and I think it's one of the most efficient ways of gaining new business. It has revolutionized the way I use internet to sell natural stone and I think it would be foolish for other suppliers not to give Slab Market a try.</p>
<p class="interview_q"><b>Slab Market:</b> Thank you for the interview Roberto, we appreciate your company’s continued business with us and wish you best of luck in the future.</p>
<img src="../img/bckgrd640b.png" alt="" width="640" height="5" border="0">    
</div>